package com.soniclink;

import com.soniclink.codec.Demodulator;
import com.soniclink.codec.Modulator;
import com.soniclink.util.BitStreamUtils;
import com.soniclink.util.SonicConfig;

import java.nio.charset.StandardCharsets;
import java.util.Arrays;

public class DemodulatorTest {

    public static void main(String[] args) {

        testSingleBit();
        testMultipleBits();
        testRoundTrip();

        System.out.println(
                "✓ DemodulatorTest: ALL TESTS PASSED"
        );
    }

    private static void testSingleBit() {

        boolean[] bits = {false};

        Modulator modulator = new Modulator();
        Demodulator demodulator = new Demodulator();

        byte[] pcm = modulator.modulate(bits);

        byte[] dataPcm = removePreamble(pcm);

        boolean[] decoded =
                demodulator.demodulate(dataPcm);

        assertBitsEqual(
                bits,
                decoded,
                "Single bit round trip failed"
        );
    }

    private static void testMultipleBits() {

        boolean[] bits = {
                false,
                true,
                false,
                true,
                true,
                false,
                true,
                false
        };

        Modulator modulator = new Modulator();
        Demodulator demodulator = new Demodulator();

        byte[] pcm = modulator.modulate(bits);

        byte[] dataPcm = removePreamble(pcm);

        boolean[] decoded =
                demodulator.demodulate(dataPcm);

        assertBitsEqual(
                bits,
                decoded,
                "Multiple bit round trip failed"
        );
    }

    private static void testRoundTrip() {

        String message = "HELLO";

        byte[] original =
                message.getBytes(StandardCharsets.UTF_8);

        boolean[] bits =
                BitStreamUtils.bytesToBits(original);

        Modulator modulator = new Modulator();
        Demodulator demodulator = new Demodulator();

        byte[] pcm =
                modulator.modulate(bits);

        byte[] dataPcm =
                removePreamble(pcm);

        boolean[] decoded =
                demodulator.demodulate(dataPcm);

        byte[] recovered =
                BitStreamUtils.bitsToBytes(decoded);

        String result =
                new String(
                        recovered,
                        StandardCharsets.UTF_8
                );

        assertTrue(
                message.equals(result),
                "Message round trip failed. Expected: "
                        + message
                        + ", got: "
                        + result
        );
    }

    /**
     * Removes the 200 ms preamble generated by Modulator.
     */
    private static byte[] removePreamble(byte[] pcm) {

        int preambleSamples =
                Math.round(
                        SonicConfig.SAMPLE_RATE
                                * SonicConfig.PREAMBLE_DURATION_MS
                                / 1000.0f
                );

        int preambleBytes =
                preambleSamples * 2;

        assertTrue(
                pcm.length > preambleBytes,
                "PCM data is shorter than the preamble"
        );

        return Arrays.copyOfRange(
                pcm,
                preambleBytes,
                pcm.length
        );
    }

    private static void assertBitsEqual(
            boolean[] expected,
            boolean[] actual,
            String message) {

        assertTrue(
                expected.length == actual.length,
                message
                        + " (length mismatch: expected "
                        + expected.length
                        + ", got "
                        + actual.length
                        + ")"
        );

        for (int i = 0; i < expected.length; i++) {

            assertTrue(
                    expected[i] == actual[i],
                    message + " at bit " + i
            );
        }
    }

    private static void assertTrue(
            boolean condition,
            String message) {

        if (!condition) {
            throw new AssertionError(message);
        }
    }
}